#translating DNA to RNA, first will use nonbiopython method
#Then will try a biopython method, so to do DNA to RNA we replace T with U
#we can use the string.replace function
#syntax: str.replace(old, new [, count]) 
#try with python first:
from Bio.Seq import Seq
def convertDNAtoRNA(s):
    #takes as input a string s and outputs a string s', where s' is the string with u instead of t
    s1= s.replace("T", "U")
    return s1

#biopython method 
my_dna= Seq("TGAGTCCTCGAGAATCAGTCTGTTGGGTAGGGCAGATTGTTGAAGCGACTATCTGACGTGCACCATTCTGTTGTCTGTTAAACAAAGATAGGGCCGGCCCATGCCCGAAAGAAGTATCATGGCAAGCACTTTTCAGAGCCCTTGAACAATCAGGATCTTCAGAGATCTGGGTTAAGTGGAGAGTCAAAATTCCCACATTCCAATTTGGCTGCAGTTCTACCGTAATCACAGGTAGCTATTTAACCGCATCGATGCACTACAGCGTTCTCAAGCCACGGCCTCCCGCAACTCCGCAGGTGCCCGTAGACTACCGCTTTTGTAGTGTTGCCAAAGCATGAGGGTCGGCGCCCATGGGTGAGCACGCGCTCGACCATAGTCGTGACCCCTAATGCGACCCCTCCCGGGATGGCGCCCATTCAGCATTAAACATGTACATATTCTCAGGGTAGGATAGGTGCGGTGTAGGATGAAGTGTGGTAGAACTCATAGACCAGCCGTCCATTACGTACTTAACCCGTGGGGGAAATAAACGTGGCGGCTCAATCAAGTTACTCAACTACGAGTGCATTCGTGCATCGATTCGGTAGGGACTTTACCTGAGACCCCGCTTGTCCAGTCCATGTGTCTCTGGTGTGGTCTGCAGCCGCGATTCATCGATCATTTGAGACCTCGCCGAAACGTAGGGTGGCGTGTCGCTGGCCCCGAGCGGGCCCCCAGCGGAGGCATCGACTTCGAGGCCCCCTGGAGCCATACGCACGGGCATCAGCATGTCTCAGTAGCAAACCACGAATTGCTGGGCGCCGGTGCGGTATTCAAAACCATTTGCTACACTGCAAGGCTCGACAGTATGTGCGGTCTAGAGAAATTCCGCTATAATGAACGGTGTAAAAAGATCACGGGGGCCATCTTTCTCTTCCGCCTATGCAACGGG")
#convert from DNA to RNA-> transcribe method 
#can also convert be backtranscribe
my_rna= my_dna.transcribe()
print(my_rna)
